# Generated by Django 6.1.1 on 2026-10-02 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('actuele_voetbalclub', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('datum_invoer', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_laatste_aanpassing', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
